version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "alpine"
      - dependency-name: "golang"
      - dependency-name: "openjdk:8*"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"