name: Dependabot PR Test
on: pull_request_target

permissions:
  contents: read

jobs:
  enableAutoMerge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        env:
          JETBRAINS_USERNAME: ${{ secrets.JETBRAINS_USERNAME }}
          JETBRAINS_PASSWORD: ${{ secrets.JETBRAINS_PASSWORD }}
        run: docker build --build-arg JETBRAINS_USERNAME --build-arg JETBRAINS_PASSWORD .
