name: Publish
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        JETBRAINS_USERNAME: ${{ secrets.JETBRAINS_USERNAME }}
        JETBRAINS_PASSWORD: ${{ secrets.JETBRAINS_PASSWORD }}
      with:
        name: lgohr/cf-jetbrains-license-server
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        snapshot: true
        buildargs: JETBRAINS_USERNAME,JETBRAINS_PASSWORD
